### ISSUE TITLE
UnrealFinderTool

### ISSUE THREAD

**Issue by Celina360** [meiskam/DDSMod#2]
Hello 😍
Will you provide me the JsonEngine configuration? I would need it to better understand the structure and to create a framework for this game

**Comment by meiskam** [comment]
I use the EngineBase.json that comes with it, no modifications

**Comment by Celina360** [comment]
how? I am getting an error. Additionally, the CoreUObject_classes.h file is empty
https://i.imgur.com/TrQIdRu.png

**Comment by meiskam** [comment]
Oh right, I forgot about that .. I edited the UFT sourcecode to silently ignore that error (and thus I'm missing about 4-5 classes because of it, I think?).  If you come up with a better solution, please share!

I've just pushed my changes here, you'll have to compile it yourself: https://github.com/meiskam/Unreal-Finder-Tool

Also, if you're trying to recreate my entire repo from scratch, you'll have to find a few things manually:
- ProcessEvent vtable entry in CoreUObject, I found the offset by opening the game exe in a debugger and poking around
- gObjectsOffset and gNamesOffset for the InitSdk function, also found in a debugger

good luck :P

**Comment by Celina360** [comment]
thank you for your help and I'll try to think of something :)
